### ISSUE TITLE
Pokelink Configuration

### ISSUE THREAD

**Issue by breadboi** [breadboi/breadboi-tv#14]
AC:
* Fix pokelink iframe as it doesn't grab data correctly on http
* Add panel to configure pokelink (possibly use a modal)

**Comment by breadboi** [comment]
This is not feasible to work on at the moment, as there is a cors related issue that must be fixed first before this can be pushed to production.

**Comment by NoelDavies** [comment]
You could download the sources ;)

**Comment by breadboi** [comment]
@NoelDavies it's open source? This would totally be a solution if so.

**Comment by NoelDavies** [comment]
https://github.com/Cysha/pokelink-web
